development:
  adapter: postgresql
  encoding: unicode
  database: shooloo_development
  pool: 5
  username: yyynyc  
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shooloo_test
  pool: 5
  username: yyynyc
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: shooloo_production
  pool: 5
  host: localhost
  username: yyynyc
  password: shooloo2013

