# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if Operation.count == 0
	Operation.create([
		{name: 'whole number', position: 1},
		{name: 'decimal point', position: 2},
		{name: 'fraction', position: 3},
		{name: 'percentage', position: 4},
		{name: 'negative number', position: 5},
		{name: 'addition', position: 6},
		{name: 'substraction', position: 7},
		{name: 'multiplication', position: 8},
		{name: 'division', position: 9}
		])
end

if Improvement.count == 0
	Improvement.create([
		{name: 'vocabulary', position: 1},
		{name: 'grammar', position: 2},
		{name: 'structure', position: 3},
		{name: 'concept clarity', position: 4},
		{name: 'originality', position: 5}
		])
end

if Flag.count == 0
	Flag.create([
		{name: 'plagerized content', position: 1},
		{name: 'offensive content', position: 2},
		{name: 'offensive image', position: 3}
		])
end

if User.count == 0
	admin1 = User.create(
		{first_name: 'Robin', 
			last_name: 'Yang',
			personal_email: 'yyynyc@gmail.com',
			grade: nil,
			screen_name: 'Elda_Hills', 
			password: 'admin1',
			password_confirmation: 'admin1', 
			privacy: true, 
			rules: true,
			role: 'tutor',
			visible: true,
			avatar: File.new(Rails.root + 'app/assets/images/Elda.jpg')}  
		)

	admin2 = User.create(
		{first_name: 'Robin',
			last_name: 'Yang',
			personal_email: 'ryang@prosperityprana.com',	
			grade: nil,
			screen_name: 'Enchanted_Collar',
			password: 'admin2',
			password_confirmation: 'admin2', 
			privacy: true,
			rules: true, 
			role: 'tutor', 
			visible: true,               
			avatar: File.new(Rails.root + 'app/assets/images/enchanted.jpg')}    
		)
	admin2.admin = true
	admin2.save!
end

if Level.count==0
	Level.create([
		{number: 0, name: 'Kindergarten'},
		{number: 1, name: '1st Grade'},
		{number: 2, name: '2nd Grade'},
		{number: 3, name: '3rd Grade'},
		{number: 4, name: '4th Grade'},
		{number: 5, name: '5th Grade'},
		{number: 6, name: '6th Grade'},
		{number: 7, name: '7th Grade'},
		{number: 8, name: '8th Grade'}
		])
end

if Domain.count==0
	Domain.create([
		{level_id: 1, name: 'Addition & Substraction (Grade K)', symbol: 'K.OA', core: 'Operations & Algebraic Thinking'},
		{level_id: 1, name: 'Number Sense & Place Value (Grade K)', symbol: 'K.NBT', core: 'Number & Operations in Based Ten'},
		{level_id: 1, name: 'Measurement & Data (Grade K)', symbol: 'K.MD', core: 'Measurement & Data'},
		{level_id: 1, name: 'Geometry (Grade K)', symbol: 'K.G', core: 'Geometry'},
		{level_id: 2, name: 'Addition & Substraction (Grade 1)', symbol: '1.OA', core: 'Operations & Algebraic Thinking' },
		{level_id: 2, name: 'Number Sense & Place Value (Grade 1)', symbol: '1.NBT', core: 'Number & Operations in Based Ten'},
		{level_id: 2, name: 'Measurement & Data (Grade 1)', symbol: '1.MD', core: 'Measurement & Data'},
		{level_id: 2, name: 'Geometry (Grade 1)', symbol: '1.G', core: 'Geometry'},
		{level_id: 3, name: 'Addition & Substraction (Grade 2)', symbol: '2.OA', core: 'Operations & Algebraic Thinking'},
		{level_id: 3, name: 'Number Sense & Place Value (Grade 2)', symbol: '2.NBT', core: 'Number & Operations in Based Ten'},
		{level_id: 3, name: 'Measurement & Data (Grade 2)', symbol: '2.MD', core: 'Measurement & Data'},
		{level_id: 3, name: 'Geometry (Grade 2)', symbol: '2.G', core: 'Geometry'},
		{level_id: 4, name: 'Multiplication & Division (Grade 3)', symbol: '3.OA', core: 'Operations & Algebraic Thinking'},
		{level_id: 4, name: 'Number Sense & Place Value (Grade 3)', symbol: '3.NBT', core: 'Number & Operations in Based Ten'},
		{level_id: 4, name: 'Measurement & Data (Grade 3)', symbol: '3.MD', core: 'Measurement & Data'},
		{level_id: 4, name: 'Geometry (Grade 3)', symbol: '3.G', core: 'Geometry'},
		{level_id: 4, name: 'Fractions (Grade 3)', symbol: '3.NF', core: 'Number & Operations-Fractions'},
		{level_id: 5, name: 'Four Operations + - x / (Grade 4)', symbol: '4.OA', core: 'Operations & Algebraic Thinking'},
		{level_id: 5, name: 'Number Sense & Place Value (Grade 4)', symbol: '4.NBT', core: 'Number & Operations in Based Ten'},
		{level_id: 5, name: 'Measurement & Data (Grade 4)', symbol: '4.MD', core: 'Measurement & Data'},
		{level_id: 5, name: 'Geometry (Grade 4)', symbol: '4.G', core: 'Geometry'},
		{level_id: 5, name: 'Fractions (Grade 4)', symbol: '4.NF', core: 'Number & Operations-Fractions'},
		{level_id: 6, name: 'Algebra (Grade 5)', symbol: '5.OA', core: 'Operations & Algebraic Thinking'},
		{level_id: 6, name: 'Place Value & Operations (Grade 5)', symbol: '5.NBT', core: 'Number & Operations in Based Ten'},
		{level_id: 6, name: 'Measurement & Data (Grade 5)', symbol: '5.MD', core: 'Measurement & Data'},
		{level_id: 6, name: 'Geometry (Grade 5)', symbol: '5.G', core: 'Geometry'},
		{level_id: 6, name: 'Fractions (Grade 5)', symbol: '5.NF', core: 'Number & Operations-Fractions'},
		{level_id: 7, name: 'Ratios & Proportions (Grade 6)', symbol: '6.RP', core: 'Ratios & Proportional Relationships'},
		{level_id: 7, name: 'Number System (Grade 6)', symbol: '6.NS', core: 'the Number System'},
		{level_id: 7, name: 'Expressions & Equations (Grade 6)', symbol: '6.EE', core: 'Expressions & Equations'},
		{level_id: 7, name: 'Geometry (Grade 6)', symbol: '6.G', core: 'Geometry'},
		{level_id: 7, name: 'Statistics & Probability (Grade 6)', symbol: '6.SP', core: 'Statistics & Probability'},
		{level_id: 8, name: 'Ratios & Proportions (Grade 7)', symbol: '7.RP', core: 'Ratios & Proportional Relationships'},
		{level_id: 8, name: 'Number System (Grade 7)', symbol: '7.NS', core: 'the Number System'},
		{level_id: 8, name: 'Expressions & Equations (Grade 7)', symbol: '7.EE', core: 'Expressions & Equations'},
		{level_id: 8, name: 'Geometry (Grade 7)', symbol: '7.G', core: 'Geometry'},
		{level_id: 8, name: 'Statistics & Probability (Grade 7)', symbol: '7.SP', core: 'Statistics & Probability'},
		{level_id: 9, name: 'Number System (Grade 8)', symbol: '8.NS', core: 'the Number System'},
		{level_id: 9, name: 'Expressions & Equations (Grade 8)', symbol: '8.EE', core: 'Expressions & Equations'},
		{level_id: 9, name: 'Geometry (Grade 8)', symbol: '8.G', core: 'Geometry'},
		{level_id: 9, name: 'Statistics & Probability (Grade 8)', symbol: '8.SP', core: 'Statistics & Probability'},
		{level_id: 9, name: 'Functions (Grade 8)', symbol: '8.F', core: 'Functions'}
		])
end


	Standard.create([
		{level_id: 1, domain_id: 1, symbol: 'CCSS.Math.Content.K.OA.A.1', short: 'K.OA.1',
			url: 'http://www.corestandards.org/Math/Content/K/OA/A/1',
			description: 'Represent addition and subtraction with objects, fingers, mental images, drawings2, sounds (e.g., claps), acting out situations, verbal explanations, expressions, or equations.',
			ICan: 'use objects, fingers and pictures to help me show addition and substraction.'},
		{level_id: 1, domain_id: 1, symbol: 'CCSS.Math.Content.K.OA.A.2', short: 'K.OA.2',
			url: 'http://www.corestandards.org/Math/Content/K/OA/A/2',
			description: 'Solve addition and subtraction word problems, and add and subtract within 10.',
			ICan: 'solve addition and subtraction word problems within 10.'},
		{level_id: 1, domain_id: 1, symbol: 'CCSS.Math.Content.K.OA.A.3', short: 'K.OA.3',
			url: 'http://www.corestandards.org/Math/Content/K/OA/A/3',
			description: 'Decompose numbers less than or equal to 10 into pairs in more than one way.',
			ICan: 'take apart numbers less than or equal to 10.'},
		{level_id: 1, domain_id: 1, symbol: 'CCSS.Math.Content.K.OA.A.4', short: 'K.OA.4',
			url: 'http://www.corestandards.org/Math/Content/K/OA/A/4',
			description: 'For any number from 1 to 9, find the number that makes 10 when added to the given number.',
			ICan: 'find the number that is added to 1 through 9 to make 10.'},
		{level_id: 1, domain_id: 1, symbol: 'CCSS.Math.Content.K.OA.A.5', short: 'K.OA.5',
			url: 'http://www.corestandards.org/Math/Content/K/OA/A/5',
			description: 'Fluently add and subtract within 5.',
			ICan: 'add and subtract within 5.'},
		{level_id: 1, domain_id: 2, symbol: 'CCSS.Math.Content.K.NBT.A.1', short: 'K.NBT.1',
			url: 'http://www.corestandards.org/Math/Content/K/NBT/A/1',
			description: 'Compose and decompose numbers from 11 to 19 into ten ones and some further ones.',
			ICan: 'put together and take apart numbers from 11 to 19 by naming the tens and ones.'},
		{level_id: 1, domain_id: 3, symbol: 'CCSS.Math.Content.K.MD.A.1', short: 'K.MD.1',
			url: 'http://www.corestandards.org/Math/Content/K/MD/A/1',
			description: 'Describe measurable attributes of objects, such as length or weight. Describe several measurable attributes of a single object.',
			ICan: 'tell how an object can be measured, e.g., by length, wideth, etc.'},
		{level_id: 1, domain_id: 3, symbol: 'CCSS.Math.Content.K.MD.A.2', short: 'K.MD.2',
			url: 'http://www.corestandards.org/Math/Content/K/MD/A/2',
			description: 'Directly compare two objects with a measurable attribute in common, to see which object has more of or less of the attribute, and describe the difference.',
			ICan: 'compare how two objects are similar or different, e.g., more of, less of, taller, shorter, etc.'},
		{level_id: 1, domain_id: 3, symbol: 'CCSS.Math.Content.K.MD.B.3', short: 'K.MD.3',
			url: 'http://www.corestandards.org/Math/Content/K/MD/B/3',
			description: 'Classify objects into given categories; count the numbers of objects in each category and sort the categories by count.',
			ICan: 'place objects into categories, count the number of objects in categories, and sort the categories by the number of objects.'},	
		{level_id: 1, domain_id: 4, symbol: 'CCSS.Math.Content.K.G.A.1', short: 'K.G.1',
			url: 'http://www.corestandards.org/Math/Content/K/G/A/1',
			description: 'Describe objects in the environment using names of shapes, and describe the relative positions of these objects using terms such as above, below, beside, in front of, behind, and next to.',
			ICan: 'find shapes around me, tell where shapes are, tell about shapes, and compare shapes'},
		{level_id: 1, domain_id: 4, symbol: 'CCSS.Math.Content.K.G.A.2', short: 'K.G.2',
			url: 'http://www.corestandards.org/Math/Content/K/G/A/2',
			description: 'Correctly name shapes regardless of their orientations or overall size..',
			ICan: 'name shapes'},
		{level_id: 1, domain_id: 4, symbol: 'CCSS.Math.Content.K.G.A.3', short: 'K.G.3',
			url: 'http://www.corestandards.org/Math/Content/K/G/A/3',
			description: 'Identify shapes as two-dimensional (lying in a plane, or flat) or three-dimensional (solid).',
			ICan: 'tell flat shapes as two-dimensional and solid shapes as three-dimensional'},
		{level_id: 1, domain_id: 4, symbol: 'CCSS.Math.Content.K.G.B.4', short: 'K.G.4',
			url: 'http://www.corestandards.org/Math/Content/K/G/B/4',
			description: 'Analyze and compare two- and three-dimensional shapes, in different sizes and orientations, using informal language to describe their similarities, differences, parts and other attributes.',
			ICan: 'compare two-dimensional and three-dimensional shapes'},
		{level_id: 1, domain_id: 4, symbol: 'CCSS.Math.Content.K.G.B.5', short: 'K.G.5',
			url: 'http://www.corestandards.org/Math/Content/K/G/B/5',
			description: 'Model shapes in the world by building shapes from components (e.g., sticks and clay balls) and drawing shapes.',
			ICan: 'make shapes using materials like sticks and clay.'},
		{level_id: 1, domain_id: 4, symbol: 'CCSS.Math.Content.K.G.B.5', short: 'K.G.5',
			url: 'http://www.corestandards.org/Math/Content/K/G/B/5',
			description: 'Model shapes in the world by building shapes from components (e.g., sticks and clay balls) and drawing shapes.',
			ICan: 'make shapes using materials like sticks and clay.'},
		{level_id: 1, domain_id: 4, symbol: 'CCSS.Math.Content.K.G.B.6', short: 'K.G.6',
			url: 'http://www.corestandards.org/Math/Content/K/G/B/6',
			description: 'Compose simple shapes to form larger shapes.',
			ICan: 'use simple shapes to make larger shapes.'},	
		{level_id: 2, domain_id: 5, symbol: 'CCSS.Math.Content.1.OA.A.1', short: '1.OA.1',
			url: 'http://www.corestandards.org/Math/Content/1/OA/A/1',
			description: 'Use addition and subtraction within 20 to solve word problems involving situations of adding to, taking from, putting together, taking apart, and comparing, with unknowns in all positions.',
			ICan: 'solve addition and substraction word problems.'},
		{level_id: 2, domain_id: 5, symbol: 'CCSS.Math.Content.1.OA.A.2', short: '1.OA.2',
			url: 'http://www.corestandards.org/Math/Content/1/OA/A/2',
			description: 'Solve word problems that call for addition of three whole numbers whose sum is less than or equal to 20.',
			ICan: 'solve word problems by adding 3 whole numbers.'},
		{level_id: 2, domain_id: 5, symbol: 'CCSS.Math.Content.1.OA.B.3', short: '1.OA.3',
			url: 'http://www.corestandards.org/Math/Content/1/OA/B/3',
			description: 'Apply properties of operations as strategies to add and subtract.',
			ICan: 'use the commutative property of addition and substraction.'},
		{level_id: 2, domain_id: 5, symbol: 'CCSS.Math.Content.1.OA.B.4', short: '1.OA.4',
			url: 'http://www.corestandards.org/Math/Content/1/OA/B/4',
			description: 'Understand subtraction as an unknown-addend problem.',
			ICan: 'use an addition fact to help me answer a subtraction problem.'},
		{level_id: 2, domain_id: 5, symbol: 'CCSS.Math.Content.1.OA.C.5', short: '1.OA.5',
			url: 'http://www.corestandards.org/Math/Content/1/OA/C/5',
			description: 'Relate counting to addition and subtraction.',
			ICan: 'count to help me add and subtract.'},
		{level_id: 2, domain_id: 5, symbol: 'CCSS.Math.Content.1.OA.C.6', short: '1.OA.6',
			url: 'http://www.corestandards.org/Math/Content/1/OA/C/6',
			description: 'Add and subtract within 20, demonstrating fluency for addition and subtraction within 10.',
			ICan: 'add and substracts facts within 20.'},
		{level_id: 2, domain_id: 5, symbol: 'CCSS.Math.Content.1.OA.D.7', short: '1.OA.7',
			url: 'http://www.corestandards.org/Math/Content/1/OA/D/7',
			description: 'Understand the meaning of the equal sign, and determine if equations involving addition and subtraction are true or false.',
			ICan: 'tell what an equal sign means and if addition and subtraction equations are true or false.'},
		{level_id: 2, domain_id: 5, symbol: 'CCSS.Math.Content.1.OA.D.8', short: '1.OA.8',
			url: 'http://www.corestandards.org/Math/Content/1/OA/D/8',
			description: 'Determine the unknown whole number in an addition or subtraction equation relating three whole numbers.',
			ICan: 'tell the missing number in an addition or subtraction problem of three whole numbers.'},
		{level_id: 2, domain_id: 6, symbol: 'CCSS.Math.Content.1.NBT.A.1', short: '1.NBT.1', 
			url: 'http://www.corestandards.org/Math/Content/1/NBT/A/1',
			description: 'Count to 120, starting at any number less than 120.', 
			ICan: 'count to 120' },
		{level_id: 2, domain_id: 6, symbol: 'CCSS.Math.Content.1.NBT.B.2', symbol: '1.NBT.2', 
			url: 'http://www.corestandards.org/Math/Content/1/NBT/B/2',
			description: 'Understand that the two digits of a two-digit number represent amounts of tens and ones.', 
			ICan: 'tell how many tens and how many ones are in a number' },
		{level_id: 2, domain_id: 6, symbol: 'CCSS.Math.Content.1.NBT.B.3', short: '1.NBT.3', 
			url: 'http://www.corestandards.org/Math/Content/1/NBT/B/3',
			description: 'Compare two two-digit numbers based on meanings of the tens and ones digits, recording the results of comparisons with the symbols >, =, and <.', 
			ICan: 'compare two-digit numbers using <, =, and >' },
		{level_id: 2, domain_id: 6, symbol: 'CCSS.Math.Content.1.NBT.C.4', short: '1.NBT.4', 
			url: 'http://www.corestandards.org/Math/Content/1/NBT/C/4',
			description: 'Add within 100, including adding a two-digit number and a one-digit number, and adding a two-digit number and a multiple of 10.', 
			ICan: 'use manipulatives, pictures, and math strategies to help me solve problems within 100.' },
		{level_id: 2, domain_id: 6, symbol: 'CCSS.Math.Content.1.NBT.C.5', short: '1.NBT.5', 
			url: 'http://www.corestandards.org/Math/Content/1/NBT/C/5',
			description: 'Given a two-digit number, mentally find 10 more or 10 less than the number, without having to count; explain the reasoning used.', 
			ICan: 'find 10 more or 10 less than a two-digit number in my head.' },
		{level_id: 2, domain_id: 6, symbol: 'CCSS.Math.Content.1.NBT.C.6', short: '1.NBT.6', 
			url: 'http://www.corestandards.org/Math/Content/1/NBT/C/6',
			description: 'Subtract multiples of 10 in the range 10-90 from multiples of 10 in the range 10-90.', 
			ICan: 'subtract multiples of 10 under 100 and explain what I did.' },
		{level_id: 2, domain_id: 7, symbol: 'CCSS.Math.Content.1.MD.A.1', short: '1.MD.1', 
			url: 'http://www.corestandards.org/Math/Content/1/MD/A/1',
			description: 'Order three objects by length; compare the lengths of two objects indirectly by using a third object.', 
			ICan: 'put three objects in order from longest to shortest.' },
		{level_id: 2, domain_id: 7, symbol: 'CCSS.Math.Content.1.MD.A.2', short: '1.MD.2', 
			url: 'http://www.corestandards.org/Math/Content/1/MD/A/2',
			description: 'Express the length of an object as a whole number of length units, by laying multiple copies of a shorter object (the length unit) end to end.', 
			ICan: 'tell the length of an object using whole numbers.' },
		{level_id: 2, domain_id: 7, symbol: 'CCSS.Math.Content.1.MD.B.3', short: '1.MD.3', 
			url: 'http://www.corestandards.org/Math/Content/1/MD/B/3',
			description: 'Tell and write time in hours and half-hours using analog and digital clocks.', 
			ICan: 'tell and write time in hours and half-hours using a clock.' },
		{level_id: 2, domain_id: 7, symbol: 'CCSS.Math.Content.1.MD.C.4', short: '1.MD.4', 
			url: 'http://www.corestandards.org/Math/Content/1/MD/C/4',
			description: 'Organize, represent, and interpret data with up to three categories; ask and answer questions about the total number of data points, how many in each category, and how many more or less are in one category than in another.', 
			ICan: 'organize, understand, and ask and answer questions about data.' },
		{level_id: 2, domain_id: 8, symbol: 'CCSS.Math.Content.1.G.A.1', short: '1.G.1', 
			url: 'http://www.corestandards.org/Math/Content/1/G/A/1',
			description: 'Distinguish between defining attributes versus non-defining attributes; build and draw shapes to possess defining attributes.', 
			ICan: 'tell about shapes and also build and draw shapes.' },
		{level_id: 2, domain_id: 8, symbol: 'CCSS.Math.Content.1.G.A.2', short: '1.G.2', 
			url: 'http://www.corestandards.org/Math/Content/1/G/A/2',
			description: 'Compose two-dimensional or three-dimensional shapes to create a composite shape, and compose new shapes from the composite shape.', 
			ICan: 'make two-dimensional and three-dimensional shapes and also use shpaes to make new shapes.' },
		{level_id: 2, domain_id: 8, symbol: 'CCSS.Math.Content.1.G.A.3', short: '1.G.3', 
			url: 'http://www.corestandards.org/Math/Content/1/G/A/3',
			description: 'Partition circles and rectangles into two and four equal shares, and describe the shares.', 
			ICan: 'divide shapes into parts.' },
		{level_id: 3, domain_id: 9, symbol: 'CCSS.Math.Content.2.OA.A.1', short: '2.OA.1', 
			url: 'http://www.corestandards.org/Math/Content/2/OA/A/1',
			description: 'Use addition and subtraction within 100 to solve one- and two-step word problems involving situations of adding to, taking from, putting together, taking apart, and comparing, with unknowns in all positions.', 
			ICan: 'use strategies to solve addition and substration word problems.' },
		{level_id: 3, domain_id: 9, symbol: 'CCSS.Math.Content.2.OA.B.2', short: '2.OA.2', 
			url: 'http://www.corestandards.org/Math/Content/2/OA/B/2',
			description: 'Fluently add and subtract within 20 using mental strategies. By end of Grade 2, know from memory all sums of two one-digit numbers.', 
			ICan: 'know my addition and substraction facts.' },
		{level_id: 3, domain_id: 9, symbol: 'CCSS.Math.Content.2.OA.C.3', short: '2.OA.3', 
			url: 'http://www.corestandards.org/Math/Content/2/OA/C/3',
			description: 'Determine whether a group of objects (up to 20) has an odd or even number of members; write an equation to express an even number as a sum of two equal addends.', 
			ICan: 'group objects to tell if a number is odd or even.' },
		{level_id: 3, domain_id: 9, symbol: 'CCSS.Math.Content.2.OA.C.4', short: '2.OA.4', 
			url: 'http://www.corestandards.org/Math/Content/2/OA/C/4',
			description: 'Use addition to find the total number of objects arranged in rectangular arrays with up to 5 rows and up to 5 columns; write an equation to express the total as a sum of equal addends.', 
			ICan: 'use repeated addition to help me understand multiplication.' },
		{level_id: 3, domain_id: 10, symbol: 'CCSS.Math.Content.2.NBT.A.1', short: '2.NBT.1', 
			url: 'http://www.corestandards.org/Math/Content/2/NBT/A/1',
			description: 'Understand that the three digits of a three-digit number represent amounts of hundreds, tens, and ones.', 
			ICan: 'understand and use hundreds, tens and ones.' },		
		{level_id: 3, domain_id: 10, symbol: 'CCSS.Math.Content.2.NBT.A.2', short: '2.NBT.2', 
			url: 'http://www.corestandards.org/Math/Content/2/NBT/A/2',
			description: 'Count within 1000; skip-count by 5s, 10s, and 100s.', 
			ICan: 'count to 1,000 using 1s, 5s, 10s and 100s.' },
		{level_id: 3, domain_id: 10, symbol: 'CCSS.Math.Content.2.NBT.A.3', short: '2.NBT.3', 
			url: 'http://www.corestandards.org/Math/Content/2/NBT/A/3',
			description: 'Read and write numbers to 1000 using base-ten numerals, number names, and expanded form.', 
			ICan: 'read and write numbers to 1,000 in different ways.' },
		{level_id: 3, domain_id: 10, symbol: 'CCSS.Math.Content.2.NBT.A.4', short: '2.NBT.4', 
			url: 'http://www.corestandards.org/Math/Content/2/NBT/A/4',
			description: 'Compare two three-digit numbers based on meanings of the hundreds, tens, and ones digits, using >, =, and < symbols to record the results of comparisons.', 
			ICan: 'compare three-digit numbers using <, =, and >.' },
		{level_id: 3, domain_id: 10, symbol: 'CCSS.Math.Content.2.NBT.B.5', short: '2.NBT.5', 
			url: 'http://www.corestandards.org/Math/Content/2/NBT/B/5',
			description: 'Fluently add and subtract within 100 using strategies based on place value, properties of operations, and/or the relationship between addition and subtraction.', 
			ICan: 'add and subtract three-digit numbers' },
		{level_id: 3, domain_id: 10, symbol: 'CCSS.Math.Content.2.NBT.B.6', short: '2.NBT.6', 
			url: 'http://www.corestandards.org/Math/Content/2/NBT/B/6',
			description: 'Add up to four two-digit numbers using strategies based on place value and properties of operations.', 
			ICan: 'add four two-digit numbers.' },
		{level_id: 3, domain_id: 10, symbol: 'CCSS.Math.Content.2.NBT.B.7', short: '2.NBT.7', 
			url: 'http://www.corestandards.org/Math/Content/2/NBT/B/7',
			description: 'Add and subtract within 1000; relate the strategy to a written method.', 
			ICan: 'add and subtract within 1000 using regrouping.' },
		{level_id: 3, domain_id: 10, symbol: 'CCSS.Math.Content.2.NBT.B.8', short: '2.NBT.8', 
			url: 'http://www.corestandards.org/Math/Content/2/NBT/B/8',
			description: 'Mentally add 10 or 100 to a given number 100-900, and mentally subtract 10 or 100 from a given number 100-900.', 
			ICan: 'add and subtract tens and hundreds in my head.' },
		{level_id: 3, domain_id: 10, symbol: 'CCSS.Math.Content.2.NBT.B.9', short: '2.NBT.9', 
			url: 'http://www.corestandards.org/Math/Content/2/NBT/B/9',
			description: 'Explain why addition and subtraction strategies work, using place value and the properties of operations.', 
			ICan: 'explain why I need to use addition or subtraction to help me solve problems. ' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.A.1', short: '2.MD.1', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/A/1',
			description: 'Measure the length of an object by selecting and using appropriate tools such as rulers, yardsticks, meter sticks, and measuring tapes.', 
			ICan: 'use different tools to measure objects.' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.A.2', short: '2.MD.2', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/A/2',
			description: 'Measure the length of an object twice, using length units of different lengths for the two measurements; describe how the two measurements relate to the size of the unit chosen.', 
			ICan: 'compare the length of an object using two different units of measurement.' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.A.3', short: '2.MD.3', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/A/3',
			description: 'Estimate lengths using units of inches, feet, centimeters, and meters.', 
			ICan: 'estimate the lengths of objects using different units of measurements.' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.A.4', short: '2.MD.4', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/A/4',
			description: 'Measure to determine how much longer one object is than another, expressing the length difference in terms of a standard length unit.', 
			ICan: 'compare the length of two different objects.' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.B.5', short: '2.MD.5', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/B/5',
			description: 'Use addition and subtraction within 100 to solve word problems involving lengths that are given in the same units.', 
			ICan: 'use addition and subtraction to solve measurement problems.' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.B.6', short: '2.MD.6', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/B/6',
			description: 'Represent whole numbers as lengths from 0 on a number line diagram with equally spaced points corresponding to the numbers 0, 1, 2, ..., and represent whole-number sums and differences within 100 on a number line diagram.', 
			ICan: 'make and use a number line.' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.C.7', short: '2.MD.7', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/C/7',
			description: 'Tell and write time from analog and digital clocks to the nearest five minutes, using a.m. and p.m.', 
			ICan: 'tell time to five minutes and understand a.m. and p.m.' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.C.8', short: '2.MD.8', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/C/8',
			description: 'Solve word problems involving dollar bills, quarters, dimes, nickels, and pennies.', 
			ICan: 'count money to help me solve word problems.' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.D.9', short: '2.MD.9', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/D/9',
			description: 'Generate measurement data by measuring lengths of several objects to the nearest whole unit, or by making repeated measurements of the same object. Show the measurements by making a line plot, where the horizontal scale is marked off in whole-number units.', 
			ICan: 'make a table to organize data and use a tble to make a line plot.' },
		{level_id: 3, domain_id: 11, symbol: 'CCSS.Math.Content.2.MD.D.10', short: '2.MD.10', 
			url: 'http://www.corestandards.org/Math/Content/2/MD/D/10',
			description: 'Draw a picture graph and a bar graph to represent a data set with up to four categories. Solve simple put-together, take-apart, and compare problems using information presented in a bar graph.', 
			ICan: 'make a graph and solve problems that have graphs.' },
		{level_id: 3, domain_id: 12, symbol: 'CCSS.Math.Content.2.G.A.1', short: '2.G.1', 
			url: 'http://www.corestandards.org/Math/Content/2/G/A/1',
			description: 'Recognize and draw shapes having specified attributes. Identify triangles, quadrilaterals, pentagons, hexagons, and cubes.', 
			ICan: 'name and draw triangles, quadrilaterals, pentagons, hexagons and cubes.' },
		{level_id: 3, domain_id: 12, symbol: 'CCSS.Math.Content.2.G.A.2', short: '2.G.2', 
			url: 'http://www.corestandards.org/Math/Content/2/G/A/2',
			description: 'Partition a rectangle into rows and columns of same-size squares and count to find the total number of them.', 
			ICan: 'find the area of a rectangle.' },
		{level_id: 3, domain_id: 12, symbol: 'CCSS.Math.Content.2.G.A.3', short: '2.G.3', 
			url: 'http://www.corestandards.org/Math/Content/2/G/A/3',
			description: 'Partition circles and rectangles into two, three, or four equal shares, describe the shares, and describe the whole. Recognize that equal shares of identical wholes need not have the same shape.', 
			ICan: 'divide shapes into equal parts and use fractions to describe the equal parts of a shape.' },
		{level_id: 4, domain_id: 13, symbol: 'CCSS.Math.Content.3.OA.A.1', short: '3.OA.1', 
			url: 'http://www.corestandards.org/Math/Content/3/OA/A/1',
			description: 'Interpret products of whole numbers, e.g., interpret 5x7 as the total number of objects in 5 groups of 7 objects each.', 
			ICan: 'understand multiplication by thinking about groups of objects.' },
		{level_id: 4, domain_id: 13, symbol: 'CCSS.Math.Content.3.OA.A.2', short: '3.OA.2', 
			url: 'http://www.corestandards.org/Math/Content/3/OA/A/2',
			description: 'Interpret whole-number quotients of whole numbers.', 
			ICan: 'understand division by thinking about how one group can be divided into smaller groups.' },
		{level_id: 4, domain_id: 13, symbol: 'CCSS.Math.Content.3.OA.A.3', short: '3.OA.3', 
			url: 'http://www.corestandards.org/Math/Content/3/OA/A/3',
			description: 'Use multiplication and division within 100 to solve word problems in situations involving equal groups, arrays, and measurement quantities.', 
			ICan: 'use what I know about multiplication and division to solve word problems.' },
		{level_id: 4, domain_id: 13, symbol: 'CCSS.Math.Content.3.OA.A.4', short: '3.OA.4', 
			url: 'http://www.corestandards.org/Math/Content/3/OA/A/4',
			description: 'Determine the unknown whole number in a multiplication or division equation relating three whole numbers.', 
			ICan: 'find the missing number in a multiplication or division equation.' },
		{level_id: 4, domain_id: 13, symbol: 'CCSS.Math.Content.3.OA.B.5', short: '3.OA.5', 
			url: 'http://www.corestandards.org/Math/Content/3/OA/B/5',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },
		{level_id: 4, domain_id: 13, symbol: 'CCSS.Math.Content.3.OA.B.6', short: '3.OA.6', 
			url: 'http://www.corestandards.org/Math/Content/3/OA/B/6',
			description: 'Understand division as an unknown-factor problem', 
			ICan: 'find the answer to a division problem by thinking of the missing factor in a multiplication problem.' },
		{level_id: 4, domain_id: 13, symbol: 'CCSS.Math.Content.3.OA.C.7', short: '3.OA.7', 
			url: 'http://www.corestandards.org/Math/Content/3/OA/C/7',
			description: 'Fluently multiply and divide within 100, using strategies such as the relationship between multiplication and division.', 
			ICan: 'multiply and divide within 100 easily and quickly because I know how multiplication and division are related.' },
		{level_id: 4, domain_id: 13, symbol: 'CCSS.Math.Content.3.OA.D.8', short: '3.OA.8', 
			url: 'http://www.corestandards.org/Math/Content/3/OA/D/8',
			description: 'Solve two-step word problems using the four operations. Represent these problems using equations with a letter standing for the unknown quantity. Assess the reasonableness of answers using mental computation and estimation strategies including rounding.', 
			ICan: 'use + - x and / to solve word problems and then use mental math and rounding to decide if my answers are reasonable.' },
		{level_id: 4, domain_id: 13, symbol: 'CCSS.Math.Content.3.OA.D.9', short: '3.OA.9', 
			url: 'http://www.corestandards.org/Math/Content/3/OA/D/9',
			description: 'Identify arithmetic patterns (including patterns in the addition table or multiplication table), and explain them using properties of operations.', 
			ICan: 'find patterns in addition and multiplication tables and explain them using what I know about how numbers work.' },
		{level_id: 4, domain_id: 14, symbol: 'CCSS.Math.Content.3.NBT.A.1', short: '3.NBT.1', 
			url: 'http://www.corestandards.org/Math/Content/3/NBT/A/1',
			description: 'Use place value understanding to round whole numbers to the nearest 10 or 100.', 
			ICan: 'round numbers to the nearest ten or hundred.' },
		{level_id: 4, domain_id: 14, symbol: 'CCSS.Math.Content.3.NBT.A.2', short: '3.NBT.2', 
			url: 'http://www.corestandards.org/Math/Content/3/NBT/A/2',
			description: 'Fluently add and subtract within 1000 using strategies and algorithms based on place value, properties of operations, and/or the relationship between addition and subtraction.', 
			ICan: 'add and subtract numbers within 1000.' },
		{level_id: 4, domain_id: 14, symbol: 'CCSS.Math.Content.3.NBT.A.3', short: '3.NBT.3', 
			url: 'http://www.corestandards.org/Math/Content/3/NBT/A/3',
			description: 'Multiply one-digit whole numbers by multiples of 10 in the range 10-90 using strategies based on place value and properties of operations.', 
			ICan: 'quickly and easily multiply any one digit whole number by 10.' },
		{level_id: 4, domain_id: 15, symbol: 'CCSS.Math.Content.3.MD.A.1', short: '3.MD.1', 
			url: 'http://www.corestandards.org/Math/Content/3/MD/A/1',
			description: 'Tell and write time to the nearest minute and measure time intervals in minutes. Solve word problems involving addition and subtraction of time intervals in minutes.', 
			ICan: 'tell and write time to the nearest minute, measure time in minutes, and solve word problems by adding and subtracting minutes.' },
		{level_id: 4, domain_id: 15, symbol: 'CCSS.Math.Content.3.MD.A.2', short: '3.MD.2', 
			url: 'http://www.corestandards.org/Math/Content/3/MD/A/2',
			description: 'Measure and estimate liquid volumes and masses of objects using standard units of grams (g), kilograms (kg), and liters (l). Add, subtract, multiply, or divide to solve one-step word problems involving masses or volumes that are given in the same units.', 
			ICan: 'measure liquids and solids with liters, grams and kilograms, and also solve word problems involving mass and volume.' },
		{level_id: 4, domain_id: 15, symbol: 'CCSS.Math.Content.3.MD.B.3', short: '3.MD.3', 
			url: 'http://www.corestandards.org/Math/Content/3/MD/B/3',
			description: 'Draw a scaled picture graph and a scaled bar graph to represent a data set with several categories. Solve one- and two-step how-many-more and how-many-less problems using information presented in scaled bar graphs.', 
			ICan: 'create a picture or bar graph to show data and solve problems using the information from the graphs.' },
		{level_id: 4, domain_id: 15, symbol: 'CCSS.Math.Content.3.MD.B.4', short: '3.MD.4', 
			url: 'http://www.corestandards.org/Math/Content/3/MD/B/4',
			description: 'Generate measurement data by measuring lengths using rulers marked with halves and fourths of an inch. Show the data by making a line plot, where the horizontal scale is marked off in appropriate units.', 
			ICan: 'create a line plot from measurement data, where the measured objects have been measured to the nearest whole number, half or quarter.' },
		{level_id: 4, domain_id: 15, symbol: 'CCSS.Math.Content.3.MD.C.5', short: '3.MD.5', 
			url: 'http://www.corestandards.org/Math/Content/3/MD/C/5',
			description: 'Recognize area as an attribute of plane figures and understand concepts of area measurement.', 
			ICan: 'understand that the area of plane shapes can be measured in square units.' },
		{level_id: 4, domain_id: 15, symbol: 'CCSS.Math.Content.3.MD.C.6', short: '3.MD.6', 
			url: 'http://www.corestandards.org/Math/Content/3/MD/C/6',
			description: 'Measure areas by counting unit squares (square cm, square m, square in, square ft, and improvised units).', 
			ICan: 'measure areas by counting unit squares.' },
		{level_id: 4, domain_id: 15, symbol: 'CCSS.Math.Content.3.MD.C.7', short: '3.MD.7', 
			url: 'http://www.corestandards.org/Math/Content/3/MD/C/7',
			description: 'Relate area to the operations of multiplication and addition.', 
			ICan: 'measure area by using what I know about multiplication and addition.' },
		{level_id: 4, domain_id: 15, symbol: 'CCSS.Math.Content.3.MD.D.8', short: '3.MD.8', 
			url: 'http://www.corestandards.org/Math/Content/3/MD/D/8',
			description: ' Solve real world and mathematical problems involving perimeters of polygons.', 
			ICan: 'solve real world math problems using what I know about the perimeter of shapes.' },
		{level_id: 4, domain_id: 16, symbol: 'CCSS.Math.Content.3.G.A.1', short: '3.G.1', 
			url: 'http://www.corestandards.org/Math/Content/3/G/A/1',
			description: 'Understand that shapes in different categories may share attributes, and that the shared attributes can define a larger category. Recognize rhombuses, rectangles, and squares as examples of quadrilaterals, and draw examples of quadrilaterals that do not belong to any of these subcategories.', 
			ICan: 'place shapes into categories depending upon their attributes and draw quadrilaterals such as rhombuses, rectangles, squares, and others.' },
		{level_id: 4, domain_id: 16, symbol: 'CCSS.Math.Content.3.G.A.2', short: '3.G.2', 
			url: 'http://www.corestandards.org/Math/Content/3/G/A/2',
			description: 'Partition shapes into parts with equal areas. Express the area of each part as a unit fraction of the whole.', 
			ICan: 'divide shapes into parts with equal areas and show those areas as fractions.' },
		{level_id: 4, domain_id: 17, symbol: 'CCSS.Math.Content.3.NF.A.1', short: '3.NF.1', 
			url: 'http://www.corestandards.org/Math/Content/3/NF/A/1',
			description: 'Understand a fraction 1/b as the quantity formed by 1 part when a whole is partitioned into b equal parts; understand a fraction a/b as the quantity formed by a parts of size 1/b.', 
			ICan: 'show and understand that fractions are equal parts of a whole.' },
		{level_id: 4, domain_id: 17, symbol: 'CCSS.Math.Content.3.NF.A.2', short: '3.NF.2', 
			url: 'http://www.corestandards.org/Math/Content/3/NF/A/2',
			description: 'Understand a fraction as a number on the number line; represent fractions on a number line diagram.', 
			ICan: 'label fractions on a number line because I know the space between any two numbers can be thought of as a whole.' },
		{level_id: 4, domain_id: 17, symbol: 'CCSS.Math.Content.3.NF.A.3', short: '3.NF.3', 
			url: 'http://www.corestandards.org/Math/Content/3/NF/A/3',
			description: 'Compare two fractions with the same numerator or the same denominator by reasoning about their size. Recognize that comparisons are valid only when the two fractions refer to the same whole. Record the results of comparisons with the symbols >, =, or <, and justify the conclusions.', 
			ICan: 'compare fractions, show whole numbers as fractions, and recognize fractions that are equal to one whole.' },
		{level_id: 5, domain_id: 18, symbol: 'CCSS.Math.Content.4.OA.A.1', short: '4.OA.1', 
			url: 'http://www.corestandards.org/Math/Content/4/OA/A/1',
			description: 'Interpret a multiplication equation as a comparison. Represent verbal statements of multiplicative comparisons as multiplication equations.', 
			ICan: 'understand that multiplication fact problems can be seen as comparisons of groups.' },
		{level_id: 5, domain_id: 18, symbol: 'CCSS.Math.Content.4.OA.A.2', short: '4.OA.2', 
			url: 'http://www.corestandards.org/Math/Content/4/OA/A/2',
			description: 'Multiply or divide to solve word problems involving multiplicative comparison, distinguishing multiplicative comparison from additive comparison.', 
			ICan: 'multiply or divide to solve word problems by using drawings or writing equations and solving for a missing number.' },
		{level_id: 5, domain_id: 18, symbol: 'CCSS.Math.Content.4.OA.A.3', short: '4.OA.3', 
			url: 'http://www.corestandards.org/Math/Content/4/OA/A/3',
			description: 'Solve multistep word problems posed with whole numbers and having whole-number answers using the four operations. Represent these problems using equations with a letter standing for the unknown quantity. Assess the reasonableness of answers using mental computation and estimation strategies including rounding.', 
			ICan: 'solve multi-step word problems involving whole numbers, represent word problems with equations, and double check my answers by using estimation, mental math and rounding.' },
		{level_id: 5, domain_id: 18, symbol: 'CCSS.Math.Content.4.OA.B.4', short: '4.OA.4', 
			url: 'http://www.corestandards.org/Math/Content/4/OA/B/4',
			description: 'Find all factor pairs for a whole number in the range 1-100. Recognize that a whole number is a multiple of each of its factors. Determine whether a given whole number in the range 1-100 is a multiple of a given one-digit number. Determine whether a given whole number in the range 1-100 is prime or composite.', 
			ICan: 'understand factors, find all factor pairs for a number from 1 to 100, and determine whether a given whole number is prime or composite.' },
		{level_id: 5, domain_id: 18, symbol: 'CCSS.Math.Content.4.OA.C.5', short: '4.OA.5', 
			url: 'http://www.corestandards.org/Math/Content/4/OA/C/5',
			description: 'Generate a number or shape pattern that follows a given rule. Identify apparent features of the pattern that were not explicit in the rule itself.', 
			ICan: 'create a number or shape pattern that follows a given rule, and notice different features of a pattern.' },
		{level_id: 5, domain_id: 19, symbol: 'CCSS.Math.Content.4.NBT.A.1', short: '4.NBT.1', 
			url: 'http://www.corestandards.org/Math/Content/4/NBT/A/1',
			description: 'Recognize that in a multi-digit whole number, a digit in one place represents ten times what it represents in the place to its right.', 
			ICan: 'recognize that in multi-digit whole number, a digit in one place represents ten times what it represents in the place to its right.' },
		{level_id: 5, domain_id: 19, symbol: 'CCSS.Math.Content.4.NBT.A.2', short: '4.NBT.2', 
			url: 'http://www.corestandards.org/Math/Content/4/NBT/A/2',
			description: 'Read and write multi-digit whole numbers using base-ten numerals, number names, and expanded form. Compare two multi-digit numbers based on meanings of the digits in each place, using >, =, and < symbols to record the results of comparisons.', 
			ICan: 'read and write larger whole numbers using numerals, words and expanded form, compare two large numbers, and use symbols to show the comparison.' },
		{level_id: 5, domain_id: 19, symbol: 'CCSS.Math.Content.4.NBT.A.3', short: '4.NBT.3', 
			url: 'http://www.corestandards.org/Math/Content/4/NBT/A/3',
			description: 'Use place value understanding to round multi-digit whole numbers to any place.', 
			ICan: 'round large whole numbers to any place, as well as add and substract large numbers.' },
		{level_id: 5, domain_id: 19, symbol: 'CCSS.Math.Content.4.NBT.B.4', short: '4.NBT.4', 
			url: 'http://www.corestandards.org/Math/Content/4/NBT/B/4',
			description: 'Fluently add and subtract multi-digit whole numbers using the standard algorithm.', 
			ICan: 'add and subtract large numbers that have multiple digits.' },
		{level_id: 5, domain_id: 19, symbol: 'CCSS.Math.Content.4.NBT.B.5', short: '4.NBT.5', 
			url: 'http://www.corestandards.org/Math/Content/4/NBT/B/5',
			description: 'Multiply a whole number of up to four digits by a one-digit whole number, and multiply two two-digit numbers. Illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.', 
			ICan: 'multiply a four-digit whole number by a one-digit whole number, and multiply two two-digit numbers.' },
		{level_id: 5, domain_id: 19, symbol: 'CCSS.Math.Content.4.NBT.B.6', short: '4.NBT.6', 
			url: 'http://www.corestandards.org/Math/Content/4/NBT/B/6',
			description: 'Find whole-number quotients and remainders with up to four-digit dividends and one-digit divisors. Illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.', 
			ICan: 'find whole-number quotients and remainders with up to four-digit dividends and one-digit divisors.' },
		{level_id: 5, domain_id: 20, symbol: 'CCSS.Math.Content.4.MD.A.1', short: '4.MD.1', 
			url: 'http://www.corestandards.org/Math/Content/4/MD/A/1',
			description: 'Know relative sizes of measurement units within one system of units. Within a single system of measurement, express measurements in a larger unit in terms of a smaller unit. Record measurement equivalents in a two-column table.', 
			ICan: 'tell the relative size of measurement units within a single system, show the measurements of a larger unit in terms of smaller units, and record these in a table.' },
		{level_id: 5, domain_id: 20, symbol: 'CCSS.Math.Content.4.MD.A.2', short: '4.MD.2', 
			url: 'http://www.corestandards.org/Math/Content/4/MD/A/2',
			description: 'Use the four operations to solve word problems involving distances, intervals of time, liquid volumes, masses of objects, and money. Represent measurement quantities using diagrams.', 
			ICan: 'use + - x and / to solve word problems involving measurement, including simple fractions and decimals.' },
		{level_id: 5, domain_id: 20, symbol: 'CCSS.Math.Content.4.MD.A.3', short: '4.MD.3', 
			url: 'http://www.corestandards.org/Math/Content/4/MD/A/3',
			description: 'Apply the area and perimeter formulas for rectangles in real world and mathematical problems.', 
			ICan: 'use what I know about area and perimeter to solve real world problems involving rectangles.' },
		{level_id: 5, domain_id: 20, symbol: 'CCSS.Math.Content.4.MD.B.4', short: '4.MD.4', 
			url: 'http://www.corestandards.org/Math/Content/4/MD/B/4',
			description: 'Make a line plot to display a data set of measurements in fractions of a unit. Solve problems involving addition and subtraction of fractions by using information presented in line plots.', 
			ICan: 'make a line plot to show measurements involving fractions, and solve problems by using information shown in line plots.' },
		{level_id: 5, domain_id: 20, symbol: 'CCSS.Math.Content.4.MD.C.5', short: '4.MD.5', 
			url: 'http://www.corestandards.org/Math/Content/4/MD/C/5',
			description: 'Recognize angles as geometric shapes that are formed wherever two rays share a common endpoint, and understand concepts of angle measurement.', 
			ICan: 'understand what angles are and know how how to measure them.' },
		{level_id: 5, domain_id: 20, symbol: 'CCSS.Math.Content.4.MD.C.6', short: '4.MD.6', 
			url: 'http://www.corestandards.org/Math/Content/4/MD/C/6',
			description: 'Measure angles in whole-number degrees using a protractor. Sketch angles of specified measure.', 
			ICan: 'use a protractor to measure angles in whole-number degrees' },
		{level_id: 5, domain_id: 20, symbol: 'CCSS.Math.Content.4.MD.C.7', short: '4.MD.7', 
			url: 'http://www.corestandards.org/Math/Content/4/MD/C/7',
			description: 'Recognize angle measure as additive. Solve addition and subtraction problems to find unknown angles on a diagram in real world and mathematical problems.', 
			ICan: 'solve addition and subtraction problems involving angles.' },
		{level_id: 5, domain_id: 21, symbol: 'CCSS.Math.Content.4.G.A.1', short: '4.G.1', 
			url: 'http://www.corestandards.org/Math/Content/4/G/A/1',
			description: 'Draw points, lines, line segments, rays, angles (right, acute, obtuse), and perpendicular and parallel lines. Identify these in two-dimensional figures.', 
			ICan: 'identify and draw points, lines, line segments, rays, angles, and perpendicular & parallel lines.' },
		{level_id: 5, domain_id: 21, symbol: 'CCSS.Math.Content.4.G.A.2', short: '4.G.2', 
			url: 'http://www.corestandards.org/Math/Content/4/G/A/2',
			description: 'Classify two-dimensional figures based on the presence or absence of parallel or perpendicular lines, or the presence or absence of angles of a specified size. Recognize right triangles as a category, and identify right triangles.', 
			ICan: 'classify two-dimensional shapes based on their geometrical attributes, and identify right triangles.' },
		{level_id: 5, domain_id: 21, symbol: 'CCSS.Math.Content.4.G.A.3', short: '4.G.3', 
			url: 'http://www.corestandards.org/Math/Content/4/G/A/3',
			description: 'Recognize a line of symmetry for a two-dimensional figure as a line across the figure such that the figure can be folded along the line into matching parts. Identify line-symmetric figures and draw lines of symmetry.', 
			ICan: 'recognize and draw lines of symmetry.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.A.1', short: '4.NF.1', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/A/1',
			description: 'Explain why a fraction a/b is equivalent to a fraction (n x a)/(n x b) by using visual fraction models. Use this principle to recognize and generate equivalent fractions.', 
			ICan: 'explain why multiplying a numerator and a denominator by the same number does not change the value of a fraction.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.A.2', short: '4.NF.2', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/A/2',
			description: 'Compare two fractions with different numerators and different denominators. Recognize that comparisons are valid only when the two fractions refer to the same whole. Record the results of comparisons with symbols and justify the conclusions.', 
			ICan: 'compare two fractions with different numerators and different denominators, record the comparison with symbols, and justify the comparison with models.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.B.3', short: '4.NF.3', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/B/3',
			description: 'Understand a fraction a/b with a > 1 as a sum of fractions 1/b.', 
			ICan: 'understand a fraction a/b with a > 1 as a sum of fractions 1/b.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.B.3a', short: '4.NF.3a', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/B/3/a',
			description: 'Understand addition and subtraction of fractions as joining and separating parts referring to the same whole.', 
			ICan: 'understand addition and subtraction of fractions as joining and separating parts referring to the same whole.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.B.3b', short: '4.NF.3b', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/B/3/b',
			description: 'Decompose a fraction into a sum of fractions with the same denominator in more than one way, recording each decomposition by an equation. Justify decompositions.', 
			ICan: 'decompose a fraction into a sum of fractions with the same denominator.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.B.3c', short: '4.NF.3c', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/B/3/c',
			description: 'Add and subtract mixed numbers with like denominators, e.g., by replacing each mixed number with an equivalent fraction, and/or by using properties of operations and the relationship between addition and subtraction.', 
			ICan: 'add and subtract mixed numbers with like denominators.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.B.3d', short: '4.NF.3d', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/B/3/d',
			description: 'Solve word problems involving addition and subtraction of fractions referring to the same whole and having like denominators.', 
			ICan: 'solve word problems involving addition and subtraction of fractions with like denominators.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.B.4', short: '4.NF.4', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/B/4',
			description: 'Apply and extend previous understandings of multiplication to multiply a fraction by a whole number.', 
			ICan: 'solve word problems involving multiplication of a fraction by a whole number.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.C.5', short: '4.NF.5', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/C/5',
			description: 'Express a fraction with denominator 10 as an equivalent fraction with denominator 100, and use this technique to add two fractions with respective denominators 10 and 100.', 
			ICan: 'show a fraction with a denominator of 10 as an equivalent fraction with a denominator of 100 in order to add the two fractions.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.C.6', short: '4.NF.6', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/C/6',
			description: 'Use decimal notation for fractions with denominators 10 or 100.', 
			ICan: 'use decimals to show fractions with denominators of 10 and 100.' },
		{level_id: 5, domain_id: 22, symbol: 'CCSS.Math.Content.4.NF.C.7', short: '4.NF.7', 
			url: 'http://www.corestandards.org/Math/Content/4/NF/C/7',
			description: 'Compare two decimals to hundredths. Recognize that comparisons are valid only when the two decimals refer to the same whole. Record the results of comparisons with the symbols, and justify the conclusions.', 
			ICan: 'compare two decimals to hundredths, record the comparison with symbols, and justify my conclusion.' },
		{level_id: 6, domain_id: 23, symbol: 'CCSS.Math.Content.5.OA.A.1', short: '5.OA.1', 
			url: 'http://www.corestandards.org/Math/Content/5/OA/A/1',
			description: 'Use parentheses, brackets, or braces in numerical expressions, and evaluate expressions with these symbols.', 
			ICan: 'use parentheses and brackets in expressions.' },
		{level_id: 6, domain_id: 23, symbol: 'CCSS.Math.Content.5.OA.A.2', short: '5.OA.2', 
			url: 'http://www.corestandards.org/Math/Content/5/OA/A/2',
			description: 'Write simple expressions that record calculations with numbers, and interpret numerical expressions without evaluating them.', 
			ICan: 'write expressions I hear using mathematic symbols and the order of operations.' },
		{level_id: 6, domain_id: 23, symbol: 'CCSS.Math.Content.5.OA.B.3', short: '5.OA.3', 
			url: 'http://www.corestandards.org/Math/Content/5/OA/B/3',
			description: 'Generate two numerical patterns using two given rules. Identify apparent relationships between corresponding terms. Form ordered pairs consisting of corresponding terms from the two patterns, and graph the ordered pairs on a coordinate plane.', 
			ICan: 'use numerical rules and patterns to form ordered pairs and graph the ordered pairs on a coordinate plane.' },
		{level_id: 6, domain_id: 24, symbol: 'CCSS.Math.Content.5.NBT.A.1', short: '5.NBT.1', 
			url: 'http://www.corestandards.org/Math/Content/5/NBT/A/1',
			description: 'Recognize that in a multi-digit number, a digit in one place represents 10 times as much as it represents in the place to its right and 1/10 of what it represents in the place to its left.', 
			ICan: 'understand and explain the value of digits.' },
		{level_id: 6, domain_id: 24, symbol: 'CCSS.Math.Content.5.NBT.A.2', short: '5.NBT.2', 
			url: 'http://www.corestandards.org/Math/Content/5/NBT/A/2',
			description: 'Explain patterns in the number of zeros of the product when multiplying a number by powers of 10, and explain patterns in the placement of the decimal point when a decimal is multiplied or divided by a power of 10. Use whole-number exponents to denote powers of 10.', 
			ICan: 'explain patterns when a number (whole number or decimal) is multiplied or divided by a power of 10.' },
		{level_id: 6, domain_id: 24, symbol: 'CCSS.Math.Content.5.NBT.A.3', short: '5.NBT.3', 
			url: 'http://www.corestandards.org/Math/Content/5/NBT/A/3',
			description: 'Read, write, and compare decimals to thousandths.', 
			ICan: 'read, write, and compare decimals to thousandths.' },
		{level_id: 6, domain_id: 24, symbol: 'CCSS.Math.Content.5.NBT.A.4', short: '5.NBT.4', 
			url: 'http://www.corestandards.org/Math/Content/5/NBT/A/4',
			description: 'Use place value understanding to round decimals to any place.', 
			ICan: 'use place value understanding to round decimals to any place.' },
		{level_id: 6, domain_id: 24, symbol: 'CCSS.Math.Content.5.NBT.B.5', short: '5.NBT.5', 
			url: 'http://www.corestandards.org/Math/Content/5/NBT/B/5',
			description: 'Fluently multiply multi-digit whole numbers using the standard algorithm.', 
			ICan: 'multiply multi-digit whole numbers.' },
		{level_id: 6, domain_id: 24, symbol: 'CCSS.Math.Content.5.NBT.B.6', short: '5.NBT.6', 
			url: 'http://www.corestandards.org/Math/Content/5/NBT/B/6',
			description: 'Find whole-number quotients of whole numbers with up to four-digit dividends and two-digit divisors. Illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.', 
			ICan: 'divide four-digit dividends by two-digit divisors, as well as illustrate and explain a division problem.' },
		{level_id: 6, domain_id: 24, symbol: 'CCSS.Math.Content.5.NBT.B.7', short: '5.NBT.7', 
			url: 'http://www.corestandards.org/Math/Content/5/NBT/B/7',
			description: 'Add, subtract, multiply, and divide decimals to hundredths; relate the strategy to a written method and explain the reasoning used.', 
			ICan: 'add, subtract, multiply, and divide decimals to hundredths, adn use concrete models or drawings to explain the method used.' },
		{level_id: 6, domain_id: 25, symbol: 'CCSS.Math.Content.5.MD.A.1', short: '5.MD.1', 
			url: 'http://www.corestandards.org/Math/Content/5/MD/A/1',
			description: 'Convert among different-sized standard measurement units within a given measurement system, and use these conversions in solving multi-step, real world problems.', 
			ICan: 'convert measurements within the same measuring system and use these conversions to solve multi-step word problems.' },
		{level_id: 6, domain_id: 25, symbol: 'CCSS.Math.Content.5.MD.B.2', short: '5.MD.2', 
			url: 'http://www.corestandards.org/Math/Content/5/MD/B/2',
			description: 'Make a line plot to display a data set of measurements in fractions of a unit. Use operations on fractions for this grade to solve problems involving information presented in line plots.', 
			ICan: 'make a line plot to display data sets of measurements in fractions and solve problems with information shown on a line plot.' },
		{level_id: 6, domain_id: 25, symbol: 'CCSS.Math.Content.5.MD.C.3', short: '5.MD.3', 
			url: 'http://www.corestandards.org/Math/Content/5/MD/C.3',
			description: 'Recognize volume as an attribute of solid figures and understand concepts of volume measurement.', 
			ICan: 'understand what volume is and know how to measure volume.' },
		{level_id: 6, domain_id: 25, symbol: 'CCSS.Math.Content.5.MD.C.4', short: '5.MD.4', 
			url: 'http://www.corestandards.org/Math/Content/5/MD/C/4',
			description: 'Measure volumes by counting unit cubes, using cubic cm, cubic in, cubic ft, and improvised units.', 
			ICan: 'measure volume by counting unit cubes.' },
		{level_id: 6, domain_id: 25, symbol: 'CCSS.Math.Content.5.MD.C.5', short: '5.MD.5', 
			url: 'http://www.corestandards.org/Math/Content/5/MD/C/5',
			description: 'Relate volume to the operations of multiplication and addition and solve real world and mathematical problems involving volume.', 
			ICan: 'solve real world problems involving volume.' },
		{level_id: 6, domain_id: 26, symbol: 'CCSS.Math.Content.5.G.A.1', short: '5.G.1', 
			url: 'http://www.corestandards.org/Math/Content/5/G/A/1',
			description: 'Use axes to define a coordinate system. Understand that the first number indicates how far to travel from the origin in the direction of one axis, and the second number indicates how far to travel in the direction of the second axis, with the convention that the names of the two axes and the coordinates correspond.', 
			ICan: 'understand how to graph ordered pairs on a coordinate plane.' },
		{level_id: 6, domain_id: 26, symbol: 'CCSS.Math.Content.5.G.A.2', short: '5.G.2', 
			url: 'http://www.corestandards.org/Math/Content/5/G/A/2',
			description: 'Represent real world and mathematical problems by graphing points in the first quadrant of the coordinate plane, and interpret coordinate values of points in the context of the situation.', 
			ICan: 'graph and interpret points in the first quadrant of a coordinate plane.' },
		{level_id: 6, domain_id: 26, symbol: 'CCSS.Math.Content.5.G.B.3', short: '5.G.3', 
			url: 'http://www.corestandards.org/Math/Content/5/G/B/3',
			description: 'Understand that attributes belonging to a category of two-dimensional figures also belong to all subcategories of that category.', 
			ICan: 'classify two-dimensional shapes into categories.' },
		{level_id: 6, domain_id: 26, symbol: 'CCSS.Math.Content.5.G.B.4', short: '5.G.4', 
			url: 'http://www.corestandards.org/Math/Content/5/G/B/4',
			description: 'Classify two-dimensional figures in a hierarchy based on properties.', 
			ICan: 'classify two-dimensional shapes based on properties.' },
		{level_id: 6, domain_id: 27, symbol: 'CCSS.Math.Content.5.NF.A.1', short: '5.NF.1', 
			url: 'http://www.corestandards.org/Math/Content/5/NF/A/1',
			description: 'Add and subtract fractions with unlike denominators (including mixed numbers) by replacing given fractions with equivalent fractions in such a way as to produce an equivalent sum or difference of fractions with like denominators.', 
			ICan: 'add and subtract fractions with unlike denominators and mixed numbers.' },
		{level_id: 6, domain_id: 27, symbol: 'CCSS.Math.Content.5.NF.A.2', short: '5.NF.2', 
			url: 'http://www.corestandards.org/Math/Content/5/NF/A/2',
			description: 'Solve word problems involving addition and subtraction of fractions referring to the same whole, including cases of unlike denominators. Use benchmark fractions and number sense of fractions to estimate mentally and assess the reasonableness of answers.', 
			ICan: 'solve word problems where I add and substract fractions of unlike denominators and double check my own answer with estimates.' },
		{level_id: 6, domain_id: 27, symbol: 'CCSS.Math.Content.5.NF.B.3', short: '5.NF.3', 
			url: 'http://www.corestandards.org/Math/Content/5/NF/B/3',
			description: 'Interpret a fraction as division of the numerator by the denominator. Solve word problems involving division of whole numbers leading to answers in the form of fractions or mixed numbers.', 
			ICan: 'solve word problems where I divide whole numbers to create an answer that is a mixed number.' },
		{level_id: 6, domain_id: 27, symbol: 'CCSS.Math.Content.5.NF.B.4', short: '5.NF.4', 
			url: 'http://www.corestandards.org/Math/Content/5/NF/B/4',
			description: 'Apply and extend previous understandings of multiplication to multiply a fraction or whole number by a fraction.', 
			ICan: 'multiply a fraction or whole number by a fraction.' },
		{level_id: 6, domain_id: 27, symbol: 'CCSS.Math.Content.5.NF.B.5', short: '5.NF.5', 
			url: 'http://www.corestandards.org/Math/Content/5/NF/B/5',
			description: 'Interpret multiplication as scaling (resizing).', 
			ICan: 'think of multiplication as the scaling of a number similar to a scale on a map.' },
		{level_id: 6, domain_id: 27, symbol: 'CCSS.Math.Content.5.NF.B.6', short: '5.NF.6', 
			url: 'http://www.corestandards.org/Math/Content/5/NF/B/6',
			description: 'Solve real world problems involving multiplication of fractions and mixed numbers, e.g., by using visual fraction models or equations to represent the problem.', 
			ICan: 'solve real world problems by multiplying fractions and mixed numbers.' },
		{level_id: 6, domain_id: 27, symbol: 'CCSS.Math.Content.5.NF.B.7', short: '5.NF.7', 
			url: 'http://www.corestandards.org/Math/Content/5/NF/B/7',
			description: 'Apply and extend previous understandings of division to divide unit fractions by whole numbers and whole numbers by unit fractions.', 
			ICan: 'divide fractions by whole numbers and whole numbers by fractions.' },
		{level_id: 7, domain_id: 28, symbol: 'CCSS.Math.Content.6.RP.A.1', short: '6.RP.1', 
			url: 'http://www.corestandards.org/Math/Content/6/RP/A/1',
			description: 'Understand the concept of a ratio and use ratio language to describe a ratio relationship between two quantities.', 
			ICan: 'use a ratio to describe the relationship between two quantities.' },
		{level_id: 7, domain_id: 28, symbol: 'CCSS.Math.Content.6.RP.A.2', short: '6.RP.2', 
			url: 'http://www.corestandards.org/Math/Content/6/RP/A/2',
			description: 'Understand the concept of a unit rate a/b associated with a ratio a:b with b not equal to 0, and use rate language in the context of a ratio relationship.', 
			ICan: 'analyze the relationship between a ratio a:b and a unit rate a/b where b is not equal to 0.' },
		{level_id: 7, domain_id: 28, symbol: 'CCSS.Math.Content.6.RP.A.3', short: '6.RP.3', 
			url: 'http://www.corestandards.org/Math/Content/6/RP/A/3',
			description: 'Use ratio and rate reasoning to solve real-world and mathematical problems.', 
			ICan: 'solve real-world and mathematical problems involving ratio and rate.' },
		{level_id: 7, domain_id: 28, symbol: 'CCSS.Math.Content.6.RP.A.3a', short: '6.RP.3a', 
			url: 'http://www.corestandards.org/Math/Content/6/RP/A/3/a',
			description: 'Make tables of equivalent ratios relating quantities with whole-number measurements, find missing values in the tables, and plot the pairs of values on the coordinate plane. Use tables to compare ratios.', 
			ICan: 'plot pairs of values that represent equivalent ratios on the coordinate plane, and use tables to compare proportional quantities.' },
		{level_id: 7, domain_id: 28, symbol: 'CCSS.Math.Content.6.RP.A.3b', short: '6.RP.3b', 
			url: 'http://www.corestandards.org/Math/Content/6/RP/A/3/b',
			description: 'Solve unit rate problems including those involving unit pricing and constant speed.', 
			ICan: 'use unit rate to solve real-world problems involving unit pricing and constant speed.' },
		{level_id: 7, domain_id: 28, symbol: 'CCSS.Math.Content.6.RP.A.3c', short: '6.RP.3c', 
			url: 'http://www.corestandards.org/Math/Content/6/RP/A/3/c',
			description: 'Find a percent of a quantity as a rate per 100; solve problems involving finding the whole, given a part and the percent.', 
			ICan: 'solve real-world problems involving finding the whole, given a part and a percent.' },
		{level_id: 7, domain_id: 28, symbol: 'CCSS.Math.Content.6.RP.A.3d', short: '6.RP.3d', 
			url: 'http://www.corestandards.org/Math/Content/6/RP/A/3/d',
			description: 'Use ratio reasoning to convert measurement units; manipulate and transform units appropriately when multiplying or dividing quantities.', 
			ICan: 'apply ratio reasoning to convert measurement units by multiplying or dividing in real-world and mathematical problems.' },
		{level_id: 7, domain_id: 29, symbol: 'CCSS.Math.Content.6.NS.A.1', short: '6.NS.1', 
			url: 'http://www.corestandards.org/Math/Content/6/NS/A/1',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },
		{level_id: 7, domain_id: 29, symbol: 'CCSS.Math.Content.6.NS.A.1', short: '6.NS.1', 
			url: 'http://www.corestandards.org/Math/Content/6/NS/A/1',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },
		{level_id: 7, domain_id: 29, symbol: 'CCSS.Math.Content.6.NS.A.1', short: '6.NS.1', 
			url: 'http://www.corestandards.org/Math/Content/6/NS/A/1',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },
		{level_id: 7, domain_id: 29, symbol: 'CCSS.Math.Content.6.NS.A.1', short: '6.NS.1', 
			url: 'http://www.corestandards.org/Math/Content/6/NS/A/1',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },
		{level_id: 7, domain_id: 29, symbol: 'CCSS.Math.Content.6.NS.A.1', short: '6.NS.1', 
			url: 'http://www.corestandards.org/Math/Content/6/NS/A/1',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },
		{level_id: 7, domain_id: 29, symbol: 'CCSS.Math.Content.6.NS.A.1', short: '6.NS.1', 
			url: 'http://www.corestandards.org/Math/Content/6/NS/A/1',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },
		{level_id: 7, domain_id: 29, symbol: 'CCSS.Math.Content.6.NS.A.1', short: '6.NS.1', 
			url: 'http://www.corestandards.org/Math/Content/6/NS/A/1',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },
		{level_id: 7, domain_id: 29, symbol: 'CCSS.Math.Content.6.NS.A.1', short: '6.NS.1', 
			url: 'http://www.corestandards.org/Math/Content/6/NS/A/1',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },
		{level_id: 7, domain_id: 29, symbol: 'CCSS.Math.Content.6.NS.A.1', short: '6.NS.1', 
			url: 'http://www.corestandards.org/Math/Content/6/NS/A/1',
			description: 'Apply properties of operations as strategies to multiply and divide.', 
			ICan: 'use the Commutative, Associative, and Distributive properties of multiplication.' },

	])

